export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const FETCH_REQUESTED = 'FETCH_REQUESTED';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';
export const NESTED_SEARCH_TYPE = 'NESTED_SEARCH_TYPE';
export const NESTED_RESULTS = 'NESTED_RESULTS';
export const RESET_PAGE = 'RESET_PAGE';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const NEW_PAGE_RESULTS = 'NEW_PAGE_RESULTS';

